### Rule Selection 

disabled_rules:
  - identifier_name
  - shorthand_operator
  - multiple_closures_with_trailing_closure
  - for_where
  - nesting
  - blanket_disable_command
  - type_name
  - comment_spacing
  - orphaned_doc_comment
  - void_function_in_ternary
opt_in_rules:
  - vertical_parameter_alignment

### Rule Configuration 

cyclomatic_complexity:
  warning: 50
  error: 60

force_cast: warning
force_try: warning
type_body_length:
  warning: 300
  error: 400
function_body_length:
  warning: 60
  error: 70
line_length:
  warning: 150
  error: 200
file_length:
  warning: 500
  error: 800

large_tuple:
  warning: 3
  error: 4

### Lint Path 

included:
  - Sources
excluded:
  - Derived


